import { appendFile, mkdir, readFile, readdir, rm, stat, writeFile } from 'fs/promises'
import path from 'path'
import { randomUUID } from 'crypto'

const STORAGE_ROOT = path.join(process.cwd(), 'public', 'uploads')
const TEMP_ROOT = path.join(process.cwd(), 'data', 'uploads', 'tmp')

const assertWritableLocalStorage = () => {
  if (process.env.VERCEL) {
    throw new Error('Local file storage is not supported on Vercel. Keep read-only gallery/admin flows live, but configure object storage before enabling photo uploads in production.')
  }
}

const sanitizeName = (value = 'upload') => {
  return value
    .replace(/[^a-zA-Z0-9._-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/(^-|-$)/g, '') || 'upload'
}

const sessionDirectory = (sessionId) => path.join(TEMP_ROOT, sessionId)
const sessionMetaFile = (sessionId) => path.join(sessionDirectory(sessionId), 'meta.json')
const sessionChunkFile = (sessionId, chunkIndex) => path.join(sessionDirectory(sessionId), `${chunkIndex}.part`)

export const readSessionMeta = async (sessionId) => {
  const content = await readFile(sessionMetaFile(sessionId), 'utf8')
  return JSON.parse(content)
}

const getReceivedChunkSize = async (sessionId) => {
  const dir = sessionDirectory(sessionId)
  try {
    const entries = await readdir(dir)
    let total = 0
    for (const entry of entries) {
      if (entry.endsWith('.part')) {
        const s = await stat(path.join(dir, entry))
        total += s.size
      }
    }
    return total
  } catch {
    return 0
  }
}

export { getReceivedChunkSize }

export const localStorageDriver = {
  mode: 'local',

  async initUploadSession({ eventSlug, fileName, fileSize, mimeType, totalChunks, directory = 'events' }) {
    assertWritableLocalStorage()

    const sessionId = randomUUID()
    const dir = sessionDirectory(sessionId)

    await mkdir(dir, { recursive: true })

    await writeFile(
      sessionMetaFile(sessionId),
      JSON.stringify(
        {
          sessionId,
          eventSlug,
          fileName,
          fileSize,
          mimeType,
          totalChunks,
          directory,
          createdAt: new Date().toISOString(),
        },
        null,
        2,
      ),
      'utf8',
    )

    return {
      sessionId,
      chunkSize: 1024 * 1024,
      storageMode: 'local',
    }
  },

  async saveChunk({ sessionId, chunkIndex, chunkBuffer }) {
    assertWritableLocalStorage()

    await mkdir(sessionDirectory(sessionId), { recursive: true })
    await writeFile(sessionChunkFile(sessionId, chunkIndex), chunkBuffer)
  },

  async completeUploadSession({ sessionId, photoId }) {
    assertWritableLocalStorage()

    const meta = await readSessionMeta(sessionId)
    const extension = path.extname(meta.fileName)
    const safeBaseName = sanitizeName(path.basename(meta.fileName, extension))
    const storedName = `${photoId}-${safeBaseName}${extension}`
    const eventDirectory = path.join(STORAGE_ROOT, meta.directory || 'events', meta.eventSlug)
    const finalFilePath = path.join(eventDirectory, storedName)

    await mkdir(eventDirectory, { recursive: true })
    await writeFile(finalFilePath, Buffer.alloc(0))

    for (let index = 0; index < meta.totalChunks; index += 1) {
      const chunkPath = sessionChunkFile(sessionId, index)
      const chunkBuffer = await readFile(chunkPath)
      await appendFile(finalFilePath, chunkBuffer)
    }

    const fileStats = await stat(finalFilePath)
    await rm(sessionDirectory(sessionId), { recursive: true, force: true })

    return {
      eventSlug: meta.eventSlug,
      originalName: meta.fileName,
      storedName,
      mimeType: meta.mimeType,
      size: fileStats.size,
      url: `/uploads/${meta.directory || 'events'}/${meta.eventSlug}/${storedName}`,
      storageMode: 'local',
    }
  },

  async deleteStoredFile(url) {
    if (!url) {
      return
    }

    // Decode percent-encoding once to catch obfuscated traversal (e.g. %2e%2e).
    // Treat a malformed sequence as an invalid path.
    let decoded
    try {
      decoded = decodeURIComponent(url)
    } catch {
      throw new Error('Invalid file path: malformed percent-encoding')
    }

    // Normalize backslashes to forward slashes before any segment checks.
    const normalized = decoded.replace(/\\/g, '/')

    // Reject NUL bytes, which can truncate paths on some platforms.
    if (normalized.includes('\0')) {
      throw new Error('Invalid file path: null byte detected')
    }

    // All URLs produced by SnapRooms start with /uploads/ — reject anything else,
    // including sibling directories such as /uploads-evil/.
    if (!normalized.startsWith('/uploads/')) {
      throw new Error('Invalid file path: must begin with /uploads/')
    }

    // Split into non-empty segments and explicitly reject any dot segment.
    // This check is intentional even when the resolved path would remain inside
    // STORAGE_ROOT: URLs generated by the application never contain dot segments,
    // so their presence always indicates a malformed or malicious input.
    const segments = normalized.split('/').filter(Boolean)
    for (const segment of segments) {
      if (segment === '.' || segment === '..') {
        throw new Error('Invalid file path: dot segments not allowed')
      }
    }

    // Require at least one path component beyond the 'uploads' prefix,
    // so that /uploads/ itself (no filename) is rejected.
    if (segments.length < 2) {
      throw new Error('Invalid file path: no file specified under /uploads/')
    }

    // Reconstruct the absolute path from the sanitised segments.
    const resolvedPath = path.resolve(path.join(process.cwd(), 'public'), segments.join('/'))

    // Second, independent containment check via path.relative().
    // rel === ''          → resolvedPath is exactly STORAGE_ROOT (no file)
    // rel === '..'        → one directory above STORAGE_ROOT
    // rel starts '../'   → escapes STORAGE_ROOT via traversal
    // path.isAbsolute    → should never occur after path.resolve, but guard anyway
    //
    // Note: startsWith('..') alone would incorrectly reject legitimate names like
    // '..hidden' whose path.relative result begins with '..' but is not traversal.
    // Using the separator suffix ('..'+path.sep) avoids that false positive.
    const rel = path.relative(STORAGE_ROOT, resolvedPath)
    const outsideRoot =
      rel === '' ||
      rel === '..' ||
      rel.startsWith(`..${path.sep}`) ||
      path.isAbsolute(rel)
    if (outsideRoot) {
      throw new Error('Invalid file path: outside storage root')
    }

    await rm(resolvedPath, { force: true })
  },
}
